version: "3.8"

networks:
  traefik_proxy:
    external: true

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      # DNS ports - bind to both host IP and Tailscale IP
      - "${HOST_IP:-0.0.0.0}:53:53/tcp"
      - "${HOST_IP:-0.0.0.0}:53:53/udp"
      - "${TAILSCALE_IP}:53:53/tcp"
      - "${TAILSCALE_IP}:53:53/udp"
      # DNS over TLS
      - "${HOST_IP:-0.0.0.0}:853:853/tcp"
      - "${TAILSCALE_IP}:853:853/tcp"
      # DNS over QUIC
      - "${HOST_IP:-0.0.0.0}:784:784/udp"
      - "${TAILSCALE_IP}:784:784/udp"
      # Web interface (initial setup)
      - "3000:3000/tcp"
      # Web interface (after setup)
      - "8001:80/tcp"  # Changed from 80 to avoid conflicts
      - "8443:443/tcp" # Changed from 443 to avoid conflicts
    volumes:
      - /mnt/user/appdata/adguardhome/work:/opt/adguardhome/work
      - /mnt/user/appdata/adguardhome/conf:/opt/adguardhome/conf
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      # Initial setup UI
      - "traefik.http.routers.adguard-setup.rule=Host(`adguard-setup.${DOMAIN_NAME}`)"
      - "traefik.http.routers.adguard-setup.entrypoints=websecure"
      - "traefik.http.routers.adguard-setup.tls=true"
      - "traefik.http.routers.adguard-setup.tls.certresolver=letsencrypt"
      - "traefik.http.services.adguard-setup.loadbalancer.server.port=3000"
      # Main UI (after setup)
      - "traefik.http.routers.adguard.rule=Host(`adguard.${DOMAIN_NAME}`)"
      - "traefik.http.routers.adguard.entrypoints=websecure"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.http.routers.adguard.tls.certresolver=letsencrypt"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
    environment:
      - TZ=${TZ:-Europe/Warsaw}
    # DNS configuration
    dns:
      - 127.0.0.1  # Use itself for DNS resolution
      - 1.1.1.1    # Fallback to Cloudflare
    # Healthcheck to ensure the service is running properly
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
