########################
# 1️⃣  Youtube Exit-node tunnel #
########################
services:
  gluetun-exit:               # ProtonVPN (Albania, for Tailscale)
    image: qmcgaw/gluetun:latest
    container_name: gluetun-exit
    network_mode: "bridge"
    cap_add: [NET_ADMIN]
    env_file:
      - ./.env
    devices: ["/dev/net/tun:/dev/net/tun"]
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WG_YT_PRIVATE_KEY}
      WIREGUARD_PUBLIC_KEY: ${WG_YT_PUBLIC_KEY}
      WIREGUARD_ADDRESSES: 10.2.0.2/32
      WIREGUARD_ALLOWED_IPS: 0.0.0.0/0
      # Server selection - be more specific with server selection
      SERVER_COUNTRIES: Albania
      # Timeouts and retries
      WIREGUARD_ENDPOINT_IP_REFRESH_SECONDS: 300
      HEALTH_CHECK_SECONDS: 180
      TZ: Europe/Tirane
      FIREWALL_OUTBOUND_SUBNETS: 100.64.0.0/10,192.168.0.0/16
      LOG_LEVEL: debug
      HTTP_CONTROL_SERVER_ADDRESS: 0.0.0.0:8023  # Change from default 8000 to avoid port conflict
      VPN_TRAFFIC_PORT: "off"  # Very important - don't force all traffic through VPN
      HEALTH_SERVER_ADDRESS: 0.0.0.0:9998       # Different from the default 9999 port
      DOT: off
      FIREWALL_VPN_INPUT_PORTS: ""  # Don't block incoming connections on the VPN interface
    volumes:
      - /mnt/user/appdata/gluetun-exit:/gluetun
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/health"]
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 30s
  youtube-router:
    image: alpine:latest
    container_name: youtube-router
    depends_on:
      gluetun-exit:
        condition: service_healthy
    restart: unless-stopped
    network_mode: "service:gluetun-exit"
    volumes:
      - /mnt/user/appdata/youtube-router:/config
    command: >
      sh -c "apk add --no-cache curl ipset iptables &&
      curl -o /config/update-youtube-routes.sh https://gist.githubusercontent.com/Lackoftactics/3916b6ab75e91c38feb8ed7363ee00ce/raw/59dbe7745630bc9d316e09c44f4ea3016bbf439d/update-youtube-routes.sh &&
      chmod +x /config/update-youtube-routes.sh &&
      /config/update-youtube-routes.sh &&
      while true; do sleep 86400; /config/update-youtube-routes.sh; done"

