version: '3.8'

services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy:latest
    container_name: Dashy
    env_file:
      - ./.env
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.rule=Host(`home.fajnachata.club`)"
      - "traefik.http.routers.dashy.entrypoints=websecure"
      - "traefik.http.routers.dashy.tls=true"
      - "traefik.http.routers.dashy.tls.certresolver=letsencrypt"
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /mnt/user/appdata/dashy/conf.yml:/conf.yml
    ports:
      - 4000:8080
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  traefik_proxy:
    external: true
#     driver: macvlan
#     driver_opts:
#       # Specify the physical host interface connected to your LAN
#       parent: eth0 # <-- IMPORTANT: Change this to your actual host interface (e.g., eth0, eno1, wlan0)
#     ipam:
#       config:
#         # Define the subnet and gateway matching your LAN
#         - subnet: 192.168.0.0/24 # <-- IMPORTANT: Adjust to your LAN subnet
#     #       gateway: 192.168.0.1 # <-- IMPORTANT: Adjust to your LAN gateway
#     #       # Optional: Define IP range if needed, but static IP is set above
#     #       # ip_range: 192.168.0.192/28