version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - /mnt/user/appdata/openwebui_data:/app/backend/data
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat.rule=Host(`chat.${DOMAIN_NAME}`)"
      - "traefik.http.routers.chat.entrypoints=websecure"
      - "traefik.http.routers.chat.service=api@internal"
      - "traefik.http.routers.chat.tls=true"
      - "traefik.http.routers.chat.tls.certresolver=letsencrypt"

networks:
  traefik_proxy:
    external: true

volumes:
  openwebui_data:
